temperature_api_controllers:
    resource: '../src/Temperature/Infrastructure/Controller/Api/'
    type: annotation
    prefix: /api

temperature_web_controllers:
    resource: '../src/Temperature/Infrastructure/Controller/Web/'
    type: annotation