App\Temperature\Domain\Entity\AverageTemperature:
    type: entity
    repositoryClass: App\Temperature\Infrastructure\Doctrine\Repository\AverageTemperatureRepository
    table: average_temperature
    id:
        id:
            type: uuid
            unique: true
    fields:
        avgTemperature:
            type: decimal
            column: avg_temperature
            precision: 10
            scale: 2
            nullable: true
    embedded:
        location:
            class: App\Temperature\Domain\Entity\Location
            columnPrefix: false
